- name: yum clean
  shell: yum clean all
- name: install pip
  yum:
    name:
      - python-pip
- name: Install openstacksdk library
  pip:
    name: openstacksdk
    state: present
#    extra_args: -U    
    version: 0.12.0
- name: Create clouds.yaml file
  blockinfile:
    create: yes
    path: /etc/openstack/clouds.yaml
    block: |2
      clouds:
        ospcloud:
          auth:
            auth_url: http://192.168.0.20:5000/
            password: r3dh4t1!
            project_name: admin
            username: admin
          identity_api_version: '3.0'
          region_name: RegionOne
      ansible:
        use_hostnames: True
        expand_hostvars: False
        fail_on_errors: True
- name: Set openstack.pub authorized key from file
  authorized_key:
    user: cloud-user
    state: present
    key: "{{ lookup('file', '/root/.ssh/openstack.pub') }}"
